/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    media: Media;
    posts: Post;
    users: User;
    contactFormSubmissions: ContactFormSubmission;
    subscriberFormSubmissions: SubscriberFormSubmission;
    pages: Page;
    persons: Person;
    testimonies: Testimony;
    organizations: Organization;
  };
  globals: {
    nav: Nav;
    metadata: Metadatum;
  };
}
export interface Media {
  id: string;
  alt?: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Post {
  id: string;
  title?: string;
  author?: string | Person;
  publishedDate?: string;
  bannerImage?: string | Media;
  cardImage?: string | Media;
  content: (
    | {
        title?: string;
        id?: string;
        blockName?: string;
        blockType: 'title';
      }
    | {
        subtitle?: string;
        id?: string;
        blockName?: string;
        blockType: 'subtitle';
      }
    | {
        text?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'richText';
      }
    | {
        primary: {
          buttonDisplayText?: string;
          buttonUrl?: string;
        };
        secondary: {
          buttonDisplayText?: string;
          buttonUrl?: string;
        };
        tertiary: {
          buttonDisplayText?: string;
          buttonUrl?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        columns: {
          title?: {
            [k: string]: unknown;
          }[];
          description?: {
            [k: string]: unknown;
          }[];
          primary: {
            buttonDisplayText?: string;
            buttonUrl?: string;
          };
          formatOption?: 'transparent' | 'border' | 'card';
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'columnBlock';
      }
    | {
        rows: {
          image?: string | Media;
          title?: {
            [k: string]: unknown;
          }[];
          description?: {
            [k: string]: unknown;
          }[];
          primary: {
            buttonDisplayText?: string;
            buttonUrl?: string;
          };
          formatOption?: 'transparent' | 'border' | 'card';
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'alternatingRowBlock';
      }
    | {
        link?: string;
        id?: string;
        blockName?: string;
        blockType: 'video';
      }
    | {
        id?: string;
        blockName?: string;
        blockType: 'signUp';
      }
    | {
        organizations: {
          organization?: string | Organization;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'partnersBlock';
      }
    | {
        persons: {
          person?: string | Person;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'teamBlock';
      }
    | {
        persons: {
          person?: string | Person;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'advisorsBlock';
      }
    | {
        persons: {
          person?: string | Person;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'mentorsBlock';
      }
    | {
        testimonies: {
          testimony?: string | Testimony;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'testimoniesBlock';
      }
    | {
        photos: {
          photo?: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'Photos';
      }
    | {
        metrics: {
          value?: {
            [k: string]: unknown;
          }[];
          description?: {
            [k: string]: unknown;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'metrics';
      }
  )[];
  status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Person {
  id: string;
  image?: string | Media;
  name?: string;
  organization?: string;
  title?: string;
  description?: string;
  linkedIn?: string;
  twitter?: string;
  role?: ('advisor' | 'mentor' | 'guestSpeaker' | 'team')[];
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Organization {
  id: string;
  logo?: string | Media;
  company?: string;
  link?: string;
  role?: 'partner' | 'network';
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Testimony {
  id: string;
  image?: string | Media;
  name?: string;
  company?: string;
  role?: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface User {
  id: string;
  name?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface ContactFormSubmission {
  id: string;
  fullName: string;
  organization: string;
  email: string;
  message: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface SubscriberFormSubmission {
  id: string;
  email: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Page {
  id: string;
  slug?: string;
  sections: (
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              subtitle?: string;
              id?: string;
              blockName?: string;
              blockType: 'subtitle';
            }
          | {
              primary: {
                buttonDisplayText?: string;
                buttonUrl?: string;
              };
              secondary: {
                buttonDisplayText?: string;
                buttonUrl?: string;
              };
              tertiary: {
                buttonDisplayText?: string;
                buttonUrl?: string;
              };
              id?: string;
              blockName?: string;
              blockType: 'cta';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'firstFoldSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              columns: {
                title?: {
                  [k: string]: unknown;
                }[];
                description?: {
                  [k: string]: unknown;
                }[];
                primary: {
                  buttonDisplayText?: string;
                  buttonUrl?: string;
                };
                formatOption?: 'transparent' | 'border' | 'card';
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'columnBlock';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'columnSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              rows: {
                image?: string | Media;
                title?: {
                  [k: string]: unknown;
                }[];
                description?: {
                  [k: string]: unknown;
                }[];
                primary: {
                  buttonDisplayText?: string;
                  buttonUrl?: string;
                };
                formatOption?: 'transparent' | 'border' | 'card';
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'alternatingRowBlock';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'alternatingRowSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              organizations: {
                organization?: string | Organization;
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'partnersBlock';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'partnersSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              persons: {
                person?: string | Person;
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'teamBlock';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'teamSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              persons: {
                person?: string | Person;
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'advisorsBlock';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'advisorsSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              persons: {
                person?: string | Person;
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'mentorsBlock';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'mentorsSection';
      }
    | {
        blocks: (
          | {
              text?: {
                [k: string]: unknown;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'richText';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'richTextSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              metrics: {
                value?: {
                  [k: string]: unknown;
                }[];
                description?: {
                  [k: string]: unknown;
                }[];
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'metrics';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'metricsSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              photos: {
                photo?: string | Media;
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'Photos';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'photosSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              link?: string;
              id?: string;
              blockName?: string;
              blockType: 'video';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'videoSection';
      }
    | {
        blocks: (
          | {
              title?: string;
              id?: string;
              blockName?: string;
              blockType: 'title';
            }
          | {
              testimonies: {
                testimony?: string | Testimony;
                id?: string;
              }[];
              id?: string;
              blockName?: string;
              blockType: 'testimoniesBlock';
            }
          | {
              css?: string;
              id?: string;
              blockName?: string;
              blockType: 'styling';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'testimoniesSection';
      }
  )[];
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Nav {
  id: string;
  links: {
    text?: string;
    url?: string;
    id?: string;
  }[];
}
export interface Metadatum {
  id: string;
  discord?: string;
  twitter?: string;
  linkedIn?: string;
  youtube?: string;
}
